### ISSUE TITLE
Add a new WSOL paper

### ISSUE THREAD

**Issue by callsys** [zhiweichen0012/Weakly-Supervised-Object-Localization-Paper-List#1]
Paper name: Generative Prompt Model for Weakly Supervised Object Localization
Paper link: https://arxiv.org/abs/2307.09756
Code link: https://github.com/callsys/GenPromp
Venue: ICCV 2023
Thank you very much!

**Comment by zhiweichen0012** [comment]
Congratulations! 
The paper has been added. Thank you for your interest in this repository.
