### ISSUE TITLE
Missing paper

### ISSUE THREAD

**Issue by won-bae** [zhiweichen0012/Weakly-Supervised-Object-Localization-Paper-List#2]
Hi,

Thank you for maintaining such a useful list for the community.
I randomly ran into the list and realized somehow our paper is not in the list.

Title: Rethinking Class Activation Mapping for Weakly Supervised Object Localization
Link: https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123600613.pdf

It's been a long time since it was published but better than never!
Thank you.

**Comment by zhiweichen0012** [comment]
We really apologize for missing this novel paper. We have updated it and thank you very much for your attention!

**Comment by won-bae** [comment]
No worries at all. Thank you for having us in the list!
