### ISSUE TITLE
Missing code link

### ISSUE THREAD

**Issue by tkdguraa** [zhiweichen0012/Weakly-Supervised-Object-Localization-Paper-List#3]
First of all, thank you for maintaining this project. It’s been incredibly helpful for researchers.

While going through the repository, I noticed that a code link for a  paper **Discovering an inference recipe for weakly-supervised object localization** is missing.

Here is the link for project: https://github.com/tkdguraa/WSOL_binarize

Thank you!

**Comment by zhiweichen0012** [comment]
We have added it and truly appreciate your support and feedback!
